"""Initial hardening schema

Revision ID: ed421a3768b3
Revises: 
Create Date: 2026-03-13 12:12:46.502379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'ed421a3768b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_config',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.drop_table('tailored_resumes')
    op.drop_table('master_profiles')
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.add_column('job_listings', sa.Column('title_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_job_listings_company_id'), 'job_listings', ['company_id'], unique=False)
    op.create_index(op.f('ix_job_listings_company_name'), 'job_listings', ['company_name'], unique=False)
    op.create_index(op.f('ix_job_listings_discovered_at'), 'job_listings', ['discovered_at'], unique=False)
    op.create_index(op.f('ix_job_listings_is_dismissed'), 'job_listings', ['is_dismissed'], unique=False)
    op.create_index(op.f('ix_job_listings_location'), 'job_listings', ['location'], unique=False)
    op.create_index(op.f('ix_job_listings_match_score'), 'job_listings', ['match_score'], unique=False)
    op.create_index(op.f('ix_job_listings_source_platform'), 'job_listings', ['source_platform'], unique=False)
    op.create_index(op.f('ix_job_listings_status'), 'job_listings', ['status'], unique=False)
    op.create_index(op.f('ix_job_listings_title'), 'job_listings', ['title'], unique=False)
    op.create_index(op.f('ix_job_listings_title_hash'), 'job_listings', ['title_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_listings_title_hash'), table_name='job_listings')
    op.drop_index(op.f('ix_job_listings_title'), table_name='job_listings')
    op.drop_index(op.f('ix_job_listings_status'), table_name='job_listings')
    op.drop_index(op.f('ix_job_listings_source_platform'), table_name='job_listings')
    op.drop_index(op.f('ix_job_listings_match_score'), table_name='job_listings')
    op.drop_index(op.f('ix_job_listings_location'), table_name='job_listings')
    op.drop_index(op.f('ix_job_listings_is_dismissed'), table_name='job_listings')
    op.drop_index(op.f('ix_job_listings_discovered_at'), table_name='job_listings')
    op.drop_index(op.f('ix_job_listings_company_name'), table_name='job_listings')
    op.drop_index(op.f('ix_job_listings_company_id'), table_name='job_listings')
    op.drop_column('job_listings', 'title_hash')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.create_table('master_profiles',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('profile_data', sqlite.JSON(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tailored_resumes',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('job_id', sa.VARCHAR(), nullable=False),
    sa.Column('tailored_content', sqlite.JSON(), nullable=False),
    sa.Column('fidelity_score', sa.INTEGER(), nullable=True),
    sa.Column('google_doc_id', sa.VARCHAR(), nullable=True),
    sa.Column('google_doc_url', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job_listings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.drop_table('system_config')
    # ### end Alembic commands ###
